server:
  port: 8033
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      routes:
        - id: mobiles
          uri: http://localhost:8083/
          predicates:
            - Path=/mobileApi/**
        - id: laptops
          uri: http://localhost:8085/
          predicates:
            - Path=/laptopApi/**



