server:
  port: 8033
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      routes:
        - id: students
          uri: http://localhost:8011/
          predicates:
            - Path=/student/**
        - id: Webflux-students
          uri: http://localhost:8022/
          predicates:
            - Path=/Student/**


